---
title: "dev-figures-loc-nodscov2"
author: "Olivier GAUFRÈS"
date: "2024-07-09"
output: html_document
---

## Load helper functions and data
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Libraries
library(tidyverse)
library(ggpubr)
library(igraph)
library(viridis)
library(extrafont)
library(extrafontdb)
library(cowplot)
library(gdata)
rm(list=ls())

# Helper functions
source("helper-functions.R")

# Figure paths
fig_loc_path <- file.path("..","..", "fig", "paper")

# Input data paths
obs_data_path <- file.path("..", "..", "data", "data-nodscov2") 
sim_data_path <- file.path("..", "..", "data", "data-synthetic-graphs") 

# Load data
load(file.path(obs_data_path, "loc", "nodscov2-reconstructed-locations.rda"))
mv(from = "admission", to = "admission_obs")
mv(from = "global_location", to = "global_location_obs")
mv(from = "rooms", to = "rooms_obs")
mv(from = "begin_date", to = "begin_date_obs")
mv(from = "end_date", to = "end_date_obs")

load(file.path(sim_data_path, "loc", "nodscov2-reconstructed-locations.rda"))
mv(from = "admission", to = "admission_sim")
mv(from = "global_location", to = "global_location_sim")
mv(from = "rooms", to = "rooms_sim")
mv(from = "begin_date", to = "begin_date_sim")
mv(from = "end_date", to = "end_date_sim")
```


## Plots
### Dictionaries
```{r}
## Dictionaries
dict_rooms_simplified = dict_rooms
dict_rooms_simplified[grepl("Patient Room", dict_rooms_simplified)] = "Patient Rooms"

# dict_times = setNames(as.character(seq(begin_date, end_date-30, 30)),
#                       as.character(1:length(global_location)))
# 
# dict_id_cat = setNames(admission %>% select(id, cat) %>% pull(cat),
#                        admission %>% select(id, cat) %>% pull(id))
```

### Plot individual trajectories for randomly selected individuals and days
```{r individual trajectories}
# Load simulation data
agenda = read.csv2(file.path(sim_data_path, "input", "agenda.csv"))
paths = read.csv2(file.path(sim_data_path, "loc", "locations_long_format.csv"))

# Example of 3 individual trajectories 
set.seed(123)
individuals_to_show = c(
  sample(admission_sim$id[admission_sim$cat == "Paramedical"], 1),
  sample(admission_sim$id[admission_sim$cat == "Medical"], 1),
  sample(id_patient, 1)
  )

all_plots = vector("list", length(individuals_to_show))
k=1
for (y in individuals_to_show) {
  if (grepl("^PA-", y)) {
    days_of_presence = seq(admission_sim %>% filter(id == y) %>% pull(firstDate), 
                           admission_sim %>% filter(id == y) %>% pull(lastDate), 
                           1)
    cat_ind = "Patient"
  } else {
    days_of_presence = agenda %>% 
      filter(id == y) %>% 
      mutate(k = 1:n(), firstDate = as_date(floor_date(as_datetime(firstDate), "day")), lastDate = as_date(floor_date(as_datetime(lastDate), "day"))) %>%
      nest(.by = k) %>%
      mutate(data = map(data, unroll_days)) %>%
      unnest(data) %>%
      pull(data)
    cat_ind = paste(admission_sim$cat[admission_sim$id == y], "staff")
  }
  
  random_day = sample(unique(days_of_presence), 1)
  individual_path = data.frame(
    time = seq(begin_date_sim, end_date_sim-30, 30),
    loc = paths[[gsub("-", ".", y)]],
    cat = admission_sim$cat[admission_sim$id == y] 
    ) %>%
    filter(floor_date(time, "day") == random_day) %>%
    mutate(loc = recode(loc, !!!c(dict_rooms, "-1" = "Absent")))
  individual_cat = unique(individual_path$cat)
  
  all_plots[[k]] = ggplot(individual_path, aes(x = time, y = loc, group=cat)) +
    geom_path(col = pal[individual_cat]) +
    theme_bw() +
    labs(x = "", y = "", title = cat_ind)
  k = k+1
}
```

### Plot distribution of time spent in resting rooms/corridor stratified by category of HCW
```{r Time spent in Restroom/Corridor by HCW cat}
all_data = data.frame()

for (d in c("Synthetic network", "Observed network")) {
  if (d=="Synthetic network") {
    data_path = sim_data_path
    admission = admission_sim
    begin_date = begin_date_sim
    end_date = end_date_sim
  }
  if (d=="Observed network") {
    data_path = obs_data_path
    admission = admission_obs
    begin_date = begin_date_obs
    end_date = end_date_obs
  }
  
  ## Load location data in long format
  paths = read.csv2(file.path(data_path, "loc", "locations_long_format.csv"))
  
  ## Boxplot
  ids_to_analyze = colnames(paths)[-1]
  ids_to_analyze = ids_to_analyze[!ids_to_analyze %in% c("PA.001.0073.O.D.9", "PA.001.0115.D.P.9")]
  cumulative_time = do.call("rbind", mapply(
    function(x,y) {
       out = data.frame(
         time = floor_date(seq(begin_date, end_date-30, 30), "day"),
         loc = x
         ) %>%
         filter(loc != "-1") %>%
         mutate(loc = recode(loc, !!!dict_rooms_simplified), time = as_date(floor_date(time, "day"))) %>%
         group_by(time, loc) %>%
         # Convert time spent in each room into hours 
         summarise(time_spent = n()*30/3600, .groups = "drop") #%>%
         # filter(!time %in% floor_date(c(begin_date, end_date-24*3600, end_date), "day")) %>%
         # group_by(loc) %>%
         # summarise(time_spent = mean(time_spent), .groups = "drop") %>%
         # mutate(id = y)
       
       if (grepl("^PE-", y)) {
         time_per_day_in_ward = data.frame(
           time = floor_date(seq(begin_date, end_date-30, 30), "day"),
           loc = x
         ) %>%
           filter(loc == "-1") %>%
           mutate(time = as_date(floor_date(time, "day"))) %>%
           group_by(time) %>%
           # Convert time spent in each room into hours 
           summarise(time_in_ward = 24-n()*30/3600, .groups = "drop") %>%
           filter(time_in_ward > 0) #%>%
           # summarise(time_in_ward = median(time_in_ward), .groups = "drop") %>%
           # pull(time_in_ward)
         
         out = out %>%
           left_join(., time_per_day_in_ward, by = "time") %>%
           mutate(time_spent = time_spent / time_in_ward) %>%
           group_by(loc) %>%
           summarise(time_spent = mean(time_spent), .groups = "drop")
  
       } else {
         out = out %>%
           group_by(time) %>%
           mutate(time_spent = time_spent/sum(time_spent)) %>%
           ungroup() %>%
           group_by(loc) %>%
           summarise(time_spent = mean(time_spent), .groups = "drop")
       }
       out$id = y
       return(out)
    },
    paths[, ids_to_analyze],
    ids_to_analyze,
    SIMPLIFY = F
  ))
    
  # Same data but displayed in a different way (all locations for each individual category)
  all_data = bind_rows(
    all_data, 
    cumulative_time %>%
      mutate(
        id = gsub("\\.", "-", id),
        loc = gsub("Restroom", "resting room", loc),
        db = d
        ) %>%
      left_join(., admission %>% select(id, cat), by = "id")
  )
}


ggplot(all_data, aes(x = loc, y = time_spent, fill = loc)) +
    geom_boxplot(outliers = F) +
    geom_jitter(size = 0.1) +
    expand_limits(y = c(0,1)) +
    facet_grid(cols = vars(cat), rows = vars(db)) +
    theme_bw() +
    theme(axis.text.x = element_text(angle = 30, hjust = 1),
          axis.title.x = element_blank(), 
          legend.position = "none") +
    labs(y = "")

```


```{r}
# Final plot
p = ggarrange(
  plotlist = all_plots, labels = c("A", "", "", "C", "D"), nrow = 5
)

```
