---
title: "dev-figures-loc-nodscov2"
author: "Olivier GAUFRÈS"
date: "2024-07-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
library(lubridate)
library(igraph)
library(tidyr)
library(viridis)
library(purrr)
library(stringr)
```

```{r Paths setup}
wd <- getwd()
knitr::opts_chunk$set(root.dir = wd)
data_path <- file.path(wd,"..", "..", "data")
nodscov2_path <- file.path(data_path, "data-nodscov2") 
loc_nodscov2_path <- file.path(wd, "..", "..", "out", "loc-nodscov2")
fig_path <- file.path(loc_nodscov2_path,"..","fig")
ind_paths_path <- file.path(fig_path, "individual-paths")
if (!dir.exists(ind_paths_path)) {
  dir.create(ind_paths_path, recursive = TRUE)
}
if (!dir.exists(loc_nodscov2_path)) {
  dir.create(loc_nodscov2_path, recursive = TRUE)
}
if (!dir.exists(fig_path)) {
  dir.create(fig_path, recursive = TRUE)
}
if (!dir.exists(nodscov2_path)) {
  dir.create(nodscov2_path, recursive = TRUE)
}
```






## CUMULATIVE NUMBER OF INTERACTION OVER TIME
```{r}
p_number_int <- do.call(rbind, global_interaction) %>%
  mutate(type_int = paste0(from_status, "-", to_status)) %>%
  mutate(type_int = ifelse(type_int == "PA-PE", "PE-PA", type_int)) %>%
  filter(type_int != "PA-PA") %>%
  #filter(between(time,600, 600 + 24*60*2)) %>%
  group_by(time, type_int) %>%
  summarise(n = n()) %>%
  ggplot(aes(x=begin_date + time*30, y=n, color = type_int))+
    geom_line(linewidth = 0.3) +
    annotate("rect", xmin = as.POSIXct("2020-05-06 12:00:00"), xmax = as.POSIXct("2020-05-07 12:00:00"), ymin = -Inf, ymax = Inf, alpha = 0.3, fill = "lightgrey") +  
    annotate("rect", xmin = as.POSIXct("2020-05-06 22:00:00"), xmax = as.POSIXct("2020-05-07 06:00:00"), ymin = -Inf, ymax = Inf, alpha = 0.2, fill = "darkgrey") +
  
    theme_bw() +
    theme(axis.text.x = element_text(angle = 35, hjust = 1)) +
    labs(title = "Number of interaction over time", x = "Time", y = "Number of interactions", color = "Type of interaction") +
    scale_color_manual(values = c("PE-PA" = "orange", "PE-PE" = "purple"), 
                       labels = c("PE-PA" = "Patient - HCW", 
                                  "PE-PE" = "HCW - HCW"))

print(p_number_int)
ggsave(file = file.path(fig_path, paste0("p_number_int", ".png")), plot = p_number_int, height = 3, width = 12)
```


## DISTRIBUTION OF TIME SPENT IN RESTROOM/CORRIDOR BY CATEGORY OF HCW
```{r Time spent in Restroom/Corridor by HCW cat}
## TRUNCATE TO KEEP ONLY 24H (24/05/06 12:00 TO 24/05/07 12:00)
end_date - begin_date ##end of last interaction
new_begin_date <- begin_date + (5*60*60) ## OFFSET TO START THE DAY AT 12AM
new_end_date <- new_begin_date + (24*60*60)
print(new_end_date - new_begin_date)
t_begin <- 5*60*2 ## OFFSET t
t_end <- (t_begin + 24*60*2) - 1

load(file.path(loc_nodscov2_path,"dev-localization-nodscov2.RData")) ##overwrite admission

global_localization_bis <- global_localization

test_loc <- do.call(rbind, global_localization) %>%
  filter(between(time, 600, 600+2880)) %>%
  left_join(admission %>% select(id, cat), by = join_by(id)) %>% 
  left_join(rooms %>% distinct(id_room, .keep_all = T) %>% select(id_room, room), by = c("localization" = "id_room")) %>%
  mutate(type = ifelse(id %in% id_medical , "MEDICAL", NA)) %>%
  mutate(type = ifelse(id %in% id_paramedical , "PARAMEDICAL", type)) %>%
  mutate(type = ifelse(id %in% id_patient , "PATIENT", type)) %>%
  group_by(id, cat, localization, room, type) %>%
  summarise(
    sum_room = n() * 30,
    n = n(),
    .groups = 'drop'
  )

test_loc$room <- factor(test_loc$room, levels = c("Corridor", "Office", "Nursing station", "Medical Restroom", "Paramedical Restroom"))

# Boxplot & jittered points (Restroom & Corridor)
test_loc %>% filter(localization %in% c(19,20,21,22,23,24)) %>%
  ggplot( aes(x=type, y=sum_room/3600, fill=type)) +
    geom_boxplot() +
    scale_fill_viridis(discrete = TRUE, alpha=0.6) +
    geom_jitter(color="black", size=0.4, alpha=0.9) +
    ggh4x::facet_grid2(cols = vars(room), scales = "free_y", independent  ="y") +
    theme_bw() +
    theme(
      legend.position="none",
      plot.title = element_text(size=11),
      axis.text.x = element_text(angle = 35, hjust = 1)
    ) +
    #ggtitle("Cumulative time spent in restroom or corridor by category of HCW") +
    xlab("") +
    ylab("Cumulative time (h)")

# Violin plot (Restroom & Corridor)    
test_loc %>% filter(localization %in% c(19,20,21,22,23,24)) %>%
  ggplot( aes(x=type, y=sum_room/3600, fill=type)) +
    geom_violin() +
    geom_boxplot(width=.1) +
    scale_fill_viridis(discrete = TRUE, alpha=0.6) +
    geom_jitter(color="black", size=0.4, alpha=0.9) +
    ggh4x::facet_grid2(cols = vars(room), scales = "free_y", independent  ="y") +
    theme_bw() +
    theme(
      legend.position="none",
      plot.title = element_text(size=11),
      axis.text.x = element_text(angle = 35, hjust = 1)
    ) +
    #ggtitle("Cumulative time spent in restroom or corridor by category of HCW") +
    xlab("") +
    ylab("Cumulative time (h)")
    
# Violin plot (Restroom)
test_loc %>% filter(room == "Medical Restroom" | room == "Paramedical Restroom") %>%
  ggplot( aes(x=type, y=sum_room/3600, fill=type)) +
    geom_violin() +
    geom_boxplot(width=.1) +
    scale_fill_viridis(discrete = TRUE, alpha=0.6) +
    geom_jitter(color="black", size=0.4, alpha=0.9) +
    theme_bw() +
    theme(
      legend.position="none",
      plot.title = element_text(size=11),
      axis.text.x = element_text(angle = 35, hjust = 1)
    ) +
    #ggtitle("Cumulative time spent in Restrooms by category of HCW") +
    xlab("") +
    ylab("Cumulative time (h)")
```


## ORDERED CUMULATIVE TIME SPENT IN ROOMS
```{r}
## Cumulative time in patients rooms
patients_room <- test_loc %>% filter(localization %in% id_room_patient) %>%
  group_by(id, .drop = "group") %>% 
  summarise(sum_patient = sum(sum_room)) %>%
  mutate(sum_room = sum_patient) %>%
  mutate(room = "Patients Rooms") %>% 
  left_join(test_loc %>% distinct(id, .keep_all = T) %>% select(id,type), by = join_by("id")) %>%
  select(id, sum_room, room, type)

other_room <- test_loc %>% filter(!localization %in% id_room_patient) %>% filter(!is.na(room)) %>%
  select(id, sum_room, room, type)

total_room <- bind_rows(other_room, patients_room)
total_room$room <- factor(total_room$room, levels = c("Corridor", "Patients Rooms",  "Nursing station", "Office", "Paramedical Restroom", "Medical Restroom"))

p_cumulative_loc <- total_room %>%
  ggplot( aes(x=type, y=sum_room/3600, fill=type)) +
    geom_boxplot() +
    scale_fill_viridis(discrete = TRUE, alpha=0.6) +
    geom_jitter(color="black", size=0.4, alpha=0.9) +
    ggh4x::facet_grid2(cols = vars(room), scales = "free_y", independent  ="y") +
    theme_bw() +
    theme(
      legend.position="none",
      plot.title = element_text(size=11,hjust = 0.5),
      axis.text.x = element_text(angle = 35, hjust = 1)
    ) +
    labs(title = "Cumulative time spent in rooms", x = "", y = "Cumulative time (h)")

print(p_cumulative_loc)
ggsave(file = file.path(fig_path, paste0("cumulative-time-rooms", ".png")), plot = p_cumulative_loc, height = 5, width = 12)
```


## TEMP - Tracking individual
```{r}
paths <- do.call(rbind, global_localization) %>% filter(between(time, 600, 600+2880)) %>% ## FILTER TO KEEP ONLY THE 24H OF INTEREST
  left_join(rooms %>%
              distinct(id_room, .keep_all = T) %>%
              select(id_room,room), by = c("localization" = "id_room")) %>%
  mutate(room = ifelse(is.na(room), "-1 NOT HERE", room))


save_individual_path <- function(ind) {
  ind_cat <- ifelse(!is.na(admission[admission$id == ind, "cat"]), admission[admission$id == ind, "cat"], "patient")
  title <-paste0('Individual trajectory over time - ', ind, ' - ', ind_cat) 
  p <- ggplot(paths %>% filter(id == ind), aes(x = time * 30 + begin_date, y = room)) +
    geom_path(aes(group = id)) +  # geom_path -> connected lines
    geom_point(aes(shape = id)) +  # geom_point -> points
    labs(title = title, x = "Time", y = "Room") +
    theme_bw() +
    theme(
    plot.title = element_text(size = 25, hjust = 0.5), #
    axis.text = element_text(size = 20),
    axis.title = element_text(size = 20),
    legend.text = element_text(size = 20),
    legend.title = element_text(size = 20),
    legend.position="none") 
    
  
  # filename
  file_name <- file.path(ind_paths_path, paste0(ind,"_", ind_cat, "_fig-traj", ".png"))
  ggsave(file = file_name, plot = p, height = 6, width = 30)
}

#map -> apply function for each individual
invisible(map(id_interacting, save_individual_path))


o <- do.call(rbind,global_localization) %>% filter(id %in% id_patient) %>% group_by(id,localization) %>% summarise(n = n())
```