---
title: "dev-loc-to-RData"
output: html_document
date: "2024-07-22"
---


```{r}
## LIBRARIES
library(dplyr)
library(Rcpp)
library(tidyr)
library(data.table)
library(purrr)

##PATHS
wd <- getwd()
loc_path <- file.path(wd,'..','..', 'out','loc-nodscov2','dev-localization-nodscov2.RData')
sensibility_path <- file.path(wd,'..','..', 'out', 'sensibility-analysis')
intervention_path <- file.path(wd,'..','..', 'out', 'intervention-analysis')
```


```{r}
##########################
## LOAD DATA & CPP CODE ##
##########################
load(loc_path)
```


```{r}
##################################
## GLOBAL OBJECTS MODIFICATIONS ## 
##################################
admission_sim <- admission %>%
  mutate(info = ifelse(status == 'PE', 1,0)) %>%
  select(id,info) %>%
  mutate(id_ind = id) %>% 
  left_join(rooms, by = c('id_ind' = 'id')) %>%
  mutate(room = ifelse(info == 1, rooms[rooms$id == 'M-PM', 'id_room'], room)) %>%
  select(id,info,room)

admission_sim$info <- as.integer(admission_sim$info)
admission_sim$room <- as.integer(admission_sim$room)

env_t <- rooms %>%
  distinct(room) %>%
  mutate(env = 0) %>%
  mutate(id_room = rooms %>% distinct(id_room) %>% pull() ) %>%
  left_join(rooms %>% select(id_room, volume), by = 'id_room') %>%
  select(room, id_room, env, volume)
env_t$id_room <- as.integer(env_t$id_room)

global_environment <- lapply(1:n_subdivisions, function(t){
  return (env_t)
})
rm(env_t)

global_status = data.frame(id = admission$id, t_inf = as.integer(-1), t_incub = as.integer(-1), t_recover = as.integer(-1), inf_by = '', inf_room = as.integer(-1))
```


```{r}
#######################
## TRUNCATED OBJECTS ## 
#######################
## TRUNCATE TO KEEP ONLY 24H (24/05/06 12:00 TO 24/05/07 12:00)
end_date - begin_date ##end of last interaction
new_begin_date <- begin_date + (5*60*60) ## OFFSET TO START THE DAY AT 12AM
new_end_date <- new_begin_date + (24*60*60)
print(new_end_date - new_begin_date)
t_begin <- 5*60*2 ## OFFSET t
t_end <- (t_begin + 24*60*2) - 1


## TRUNCATED INFO
truncated_interaction <- global_interaction[(u <- seq_along(global_interaction)) %in% t_begin:(t_end)]
truncated_localization <- global_localization[(u <- seq_along(global_localization)) %in% t_begin:(t_end)]
truncated_environment <- global_environment[(u <- seq_along(global_environment)) %in% t_begin:(t_end)]
truncated_status <- global_status


## FILTER INDIVIDUALS NOT INTERACTING
id_interacting <- do.call(rbind,truncated_interaction) %>%
  pivot_longer(cols = c(from, to), names_to = 'direction', values_to = 'individual') %>%
  distinct(individual) %>%
  pull()
id_total <- admission %>% distinct(id) %>% pull()
id_not_interacting <- setdiff(id_total, id_interacting)

filter_interacting <- function(list_df, id_interacting) {
  lapply(list_df, function(df) {
    df %>% filter(id %in% id_interacting)
  })
}

admission_sim <- admission_sim %>% filter(id %in% id_interacting)
truncated_localization <- filter_interacting(truncated_localization, id_interacting )
truncated_status <- truncated_status %>% filter(id %in% id_interacting)
truncated_data <- lapply(1:length(truncated_localization), function(t){
  df <- data.frame(id = truncated_localization[[t]]$id,
                   info = admission_sim$info,
                   #room = admission_sim$room,
                   #interacting = ifelse(id %in% truncated_interaction$from | id %in% truncated_interaction$to, T, F)
                   localization_ti = truncated_localization[[t]]$localization,
                   lambda_c = 0,
                   lambda_e = 0
  )
  df <- df %>% filter(localization_ti != -1)
  return(df)
})

## ENDLESS DAY OBJECTS
n_days <- 7*10
```


```{r}
##PARAMETERS
B <- 0.48 *24 # Breathing rate (0.48 m3/h)
mu_air <- 4 * 24 # Quanta removal (4-6 Air changes/h)
mu_inac <- (log(2)/1.1) * 24 # Quanta inactivation (computed with viral half life -> 0.63 quanta inactivated/h) 
mu <- mu_air + mu_inac
nu <- 10 * 24 # (10 quanta/h)
dt <- 30 # Time step
tau <- 60 * 60 *24 # Seconds in 1 day
deltat <- dt/tau
env_threshold <- 0 # Quanta threshold above which the environment is infectious

# BETA
p_PA_PA <- 2.3e-5
p_PA_PE <- 1.19e-4
p_PE_PA <- 7.89e-4
p_PE_PE <- 1.66e-4
#p <- median(c(p_PA_PA,p_PA_PE,p_PE_PA,p_PE_PE))
p <- mean(c(p_PA_PA,p_PA_PE,p_PE_PA,p_PE_PE))
beta <- (-log(1-p))*(86400/30)
```

## SAVE
```{r}
intervention_path <- file.path(wd,'..','..', 'out', 'intervention-analysis')
dir.create(intervention_path)
save(n_days,
       truncated_interaction,
       truncated_environment,
       truncated_data,
       truncated_status,
       admission_sim,
       beta,
       B,
       nu,
       mu,
       env_threshold,
       dt,
       t_begin,
       t_end,
       file = file.path(intervention_path, paste0('parameters-model.RData'))
  )


## CP THE SENSIBILITY/FOLDER TO CLUSTER/OUT
```


## ADMISSIONS/DISCHARGES
```{r}
library(dplyr)


# Load necessary data
wd <- getwd()
intervention_path <- file.path(wd, '..', '..', 'out', 'intervention-analysis')
load(file.path(intervention_path, paste0('parameters-model.RData')))

n_days = 90
```


```{r}
##remove useless variables
truncated_interaction <- map(truncated_interaction, select, c(from,to,localization))

test_interaction <- rep(truncated_interaction, n_days)
test_environment <- rep(truncated_environment, n_days)
test_data <- rep(truncated_data, n_days)
test_status <- truncated_status
new_n_subdivisions <- (t_end - t_begin + 1) * n_days


df_data_long <- rbindlist(test_data, idcol='time')
df_data_long$time <- df_data_long$time + 599

df_interaction_long <- rbindlist(test_interaction, idcol='time')
df_interaction_long$time <- df_interaction_long$time + 599


id_patient <- admission_sim %>% 
  filter(info == 0) %>%
  pull(id)

base_id <- substr(tail(admission_sim$id, 1), 1, 4)

# Function to increment IDs
increment_id <- function(last_id, base_id) {
  last_number <- substr(last_id, 5, 8)
  new_number <- sprintf("%04d", as.numeric(last_number) + 1)
  paste0(base_id, new_number, '-N-P')
}
```


```{r}
## ADD NEW PATIENTS
for (patient in id_patient){
  i <- 600
  iter <- 0
  info_patient <- admission_sim %>% filter(id == patient)
  while (i < new_n_subdivisions & iter < 25) {
    last_id <- tail(admission_sim$id, 1)
    new_id <- increment_id(last_id, base_id)
    row_new_patient <- info_patient %>% mutate(id = new_id)
    
    i_sampled <- as.integer(runif(1, min = 6*24*60*2, max = 8*24*60*2))
    
    df_data_long[id == patient & between(time, i, i + i_sampled - 1), id := new_id]
    df_interaction_long[from == patient & between(time, i, i + i_sampled - 1), from := new_id]
    df_interaction_long[to == patient & between(time, i, i + i_sampled - 1), to := new_id]
    iter <- iter + 1
    i <- i + i_sampled
    admission_sim <- rbind(admission_sim,  row_new_patient)
    test_status <- rbind(test_status, data.frame(id = new_id,
                                                 t_inf = -1,
                                                 t_incub = -1,
                                                 t_recover = -1,
                                                 inf_by = NA,
                                                 inf_room = -1))
    
  }
  
}
```


```{r}
# df to list of df with split 
global_data <- split(df_data_long, df_data_long$time)
global_interaction <- split(df_interaction_long, df_interaction_long$time)
global_environment <- test_environment
global_status <- test_status

end_date - begin_date ##end of last interaction
new_begin_date <- begin_date + (5*60*60) ## OFFSET TO START THE DAY AT 12AM
new_end_date <- new_begin_date + (24*60*60)
print(new_end_date - new_begin_date)
t_begin <- 5*60*2 ## OFFSET t
t_end <- (t_begin + 24*60*2) - 1
```

```{r}
save_path <- file.path(intervention_path, "parameters-admission-nodscov2.RData")
save(global_interaction,,
     global_data,
     global_status,
     global_environment,
     admission_sim,
     admission,
     beta,
     nu,
     mu,
     B,
     env_threshold,
     dt,
     new_n_subdivisions,
     n_days,
     t_begin,
     t_end,
     file = save_path
)
##SMALLER RDATA
# save(global_interaction,,
#      global_data,
#      global_status,
#      truncated_environment,
#      admission_sim,
#      beta,
#      nu,
#      mu,
#      B,
#      env_threshold,
#      dt,
#      new_n_subdivisions,
#      n_days,
#      t_begin,
#      t_end,
#      file = save_path
# )
```


<!-- ###### launch_sensibility.R (CLUSTER) ######  -->
```{r}
###########
## PATHS ##
###########
beta <- 3


wd <- getwd()
loc_path <- file.path(wd,'..','..', 'out','loc-nodscov2','dev-localization-nodscov2.RData')
intervention_path <- file.path(wd, '..', '..', 'out', 'intervention-analysis')
cpp_path <- file.path(wd, '..', '..', 'cpp', 'nodscov2', 'dev-sensibility-analysis.cpp')

####################
## RDATA AND RCPP ##
####################
load(file.path(intervention_path, "parameters-admission-nodscov2.RData"))
sourceCpp(cpp_path)

################################
## CREATE ENDLESS DAY OBJECTS ##
################################
# global_interaction <- rep(truncated_interaction, n_days)
# global_environment <- rep(truncated_environment, n_days)
# global_data <- rep(truncated_data, n_days)
# global_status <- truncated_status
# new_n_subdivisions <- (t_end-t_begin +1)*n_days
```


```{r}
#######################
## RANDOM INDEX CASE ##
#######################
id_index <- sample( x = admission %>% filter(id %in% admission_sim$id) %>% distinct(id) %>% pull(), size = 1) ## index case in individuals that are here at the beginning of the simulation
# UPDATE STATUS
global_status <- global_status %>%
  mutate(t_inf = ifelse(id == id_index,
                        as.integer(1),
                        t_inf),
         t_incub = ifelse(id == id_index, 
                          as.integer(t_inf + runif(1, min = 2880*1, max = 2880*3)),
                          t_recover),
         t_recover = ifelse(id == id_index,
                            as.integer(t_incub + runif(1, min = 2880*3, max = 2880*7)),
                            t_recover),
         inf_by = ifelse(id == id_index,
                         'INDEX',
                         inf_by))
```




<!-- ################################# SIMULATION (LOCAL) #################################  -->
## SINGLE SIMULATION (dev-model)
```{r}
load()
cpp_path <- file.path(wd, '..', '..', 'cpp', 'nodscov2')
sourceCpp(file.path(cpp_path, 'dev-model-nodscov2.cpp'))
sourceCpp(file.path(cpp_path, 'dev-sensibility-analysis.cpp'))
a <-Sys.time()
data_sim <- simulation(global_interaction = global_interaction,
                     global_environment = global_environment,
                     global_data = global_data,
                     global_status = global_status,
                     beta = beta,
                     B = B,
                     nu = nu,
                     mu = mu,
                     env_threshold = env_threshold,
                     dt = dt)
b <-Sys.time()
print(b-a)


save(global_interaction,
     global_data,
     global_environment,
     admission,
     admission_sim,
     beta,
     nu,
     mu,
     B,
     env_threshold,
     dt,
     new_n_subdivisions,
     n_days,
     new_begin_date,
     new_end_date,
     t_begin,
     t_end,
     data_sim,
     file = file.path(id_sim_path, paste0(id_sim, "-", "test-unique-simulation-nodscov2.RData"))
     )
```

```{r}
args = commandArgs(trailingOnly=TRUE)
id_sim <- ifelse(length(args)==0, "dev-test-endless-day", args[1])
id_sim_path <- file.path(wd, '..', '..', 'out', 'sim-nodscov2' , id_sim)

if (!dir.exists(id_sim_path)) {
  dir.create(id_sim_path, recursive = TRUE)
}


save(truncated_interaction,
     truncated_localization,
     truncated_environment,
     admission,
     admission_sim,
     beta,
     nu,
     mu,
     B,
     env_threshold,
     dt,
     new_n_subdivisions,
     n_days,
     new_begin_date,
     new_end_date,
     t_begin,
     t_end,
     data_sim,
     file = file.path(id_sim_path, paste0(id_sim, "-", "unique-simulation-nodscov2.RData"))
     )
```




## MULTIPLE SIMULATIONS (C/E/C+E)
```{r}
n_sim <- 1
sourceCpp(file.path(cpp_path, 'dev-sensibility-analysis.cpp'))

sim_C <- replicate(n_sim, {
  simulation(
    global_interaction = global_interaction,
    global_environment = global_environment,
    global_data = global_data,
    global_status = global_status,
    beta = beta,
    B = 0,
    nu = nu,
    mu = mu,
    env_threshold = env_threshold,
    dt = dt)
}, simplify = FALSE)


sim_E <- replicate(n_sim, {
  simulation(
    global_interaction = global_interaction,
    global_environment = global_environment,
    global_data = global_data,
    global_status = global_status,
    beta = 0,
    B = B,
    nu = nu,
    mu = mu,
    env_threshold = env_threshold,
    dt = dt)
}, simplify = FALSE)


sim_C_E <- replicate(n_sim, {
  simulation(
    global_interaction = global_interaction,
    global_environment = global_environment,
    global_data = global_data,
    global_status = global_status,
    beta = beta,
    B = B,
    nu = nu,
    mu = mu,
    env_threshold = env_threshold,
    dt = dt)
}, simplify = FALSE)
```


##SAVE .RDATA
```{r}
save_path <- file.path(id_sim_path, paste0(id_sim, "-", "multiple-simulation-nodscov2.RData"))
save(sim_C,
     sim_E,
     sim_C_E,
     truncated_interaction,
     truncated_localization,
     truncated_data,
     admission,
     admission_sim,
     n_sim,
     rooms,
     beta,
     nu,
     mu,
     B,
     env_threshold,
     dt,
     new_n_subdivisions,
     n_days,
     new_begin_date,
     new_end_date,
     file = save_path
)
```




## BENCHMARK
```{r}
library(microbenchmark)
a <- microbenchmark(simulation(global_interaction = global_interaction,
                     global_environment = global_environment,
                     global_data = global_data,
                     global_status = global_status,
                     beta = beta,
                     B = B,
                     nu = nu,
                     mu = mu,
                     env_threshold = env_threshold,
                     dt = dt), times = 10)
```

