---
title: 'intervention-analysis'
author: 'Olivier GAUFRÈS'
date: '2024-07-30'
output: html_document
---

```{r}
## LIBRARIES
library(dplyr)
library(tidyr)
library(purrr)

## READ RData FILES -> STRUCTURE OF FILE: sim_<beta>_<nu>_<sim_id>.RData 
## WARNING BETA = 1/3 WILL BE WRITTEN AS 1-3
## IN THE RDATA FILE, THERE WILL BE A DATAFRAME NAMED: sim_<beta>_<nu>_<sim_id>
load_rdata_to_list <- function(file, list_sim, dir) {
  load(file.path(intervention_path, 'out', dir, 'results', file))
  file_name <- basename(file)
  parts <- strsplit(file_name, "_")[[1]]
  sim_id <- parts[length(parts)] ## last number is the sim id
  sim_id <- as.integer(sub("\\.RData$", "", sim_id))  # Remove file extension
  # beta <- eval(parse(text = gsub(pattern = '-', replacement = '/', x = parts[2])))
  # nu <- eval(parse(text = gsub(pattern = '-', replacement = '/', x = parts[3])))
  sim_object <- get(sub("\\.RData$", "", file_name))
  list_sim[[dir]][[sim_id]] <<- sim_object
}

SEIR_counts <- function(status_sim, n_subdivisions, n_individual) {
  ## Time steps
  times <- seq(1, n_subdivisions, 100)
  ##DF
  counts_df <- data.frame(
    Susceptible = colSums(outer(status_sim$t_inf, times, function(x, y) x == -1 | x > y)),
    Exposed = colSums(outer(status_sim$t_inf, times, function(x, y) x <= y) & outer(status_sim$t_incub, times, function(x, y) x > y)),
    Infectious = colSums(outer(status_sim$t_incub, times, function(x, y) x <= y) & outer(status_sim$t_recover, times, function(x, y) x > y)),
    Recovered = colSums(outer(status_sim$t_recover, times, function(x, y) x <= y) & outer(status_sim$t_inf, times, function(x, y) x != -1)),
    time = times
  )
  ## Pivot for easier plot
  counts_df <- counts_df %>%
    pivot_longer(cols = c("Susceptible", "Exposed", "Infectious", "Recovered"), names_to = "status", values_to = "count") %>%
    mutate(proportion = count * 100 / n_individual)
  ## ## S E I R as factor 
  counts_df$status <- factor(counts_df$status, levels = c("Susceptible", "Exposed", "Infectious", "Recovered"))
  
  return(counts_df)
}

SEIR_to_list <- function(sim_list, n_subdivisions, n_individual) {
  lapply(sim_list, function(status_sim) {
    SEIR_counts(status_sim, n_subdivisions, n_individual)
  })
}
```


```{r}
##PATHS
wd <- getwd()

source(file.path(wd, 'intervention-analysis_fun.R'))
out_path <- file.path(wd,'..','..', 'out')
loc_path <- file.path(out_path,'loc-nodscov2')
intervention_path <- file.path(out_path, 'intervention-analysis')
```

## LOAD LOCALIZATION DATA & GLOBAL PARAMETERS
```{r}
load(file.path(loc_path, 'dev-localization-nodscov2.RData'))
load(file.path(intervention_path, "parameters-admission-nodscov2.RData"))
##TO FIX IN loc-to-RData (rerun to update parameters.RData)
admission <- admission %>% filter(id %in% admission_sim$id)
```

## ADJUST THE BEGIN/END DATES OF SIMULATIONS
```{r}
new_begin_date <- begin_date + t_begin*30 ## OFFSET TO START THE DAY AT 12AM
new_end_date <- new_begin_date + new_n_subdivisions*30
print(new_end_date - new_begin_date)
```
## BETA/NU COUPLES -> READ SIMULATION RESULTS
```{r}
#read_all_files <- function(path, )

## ALL COUPLES INSIDE A LIST, EVERY SIMULATION INSIDE SUB-LIST NAMED sim<beta>_<nu> --> WILL BE NAMED A COUPLE
list_dirs <- list.dirs(path = file.path(intervention_path, 'out'), recursive = F, full.names = F)
list_sim <- list()

## READ ALL SIMULATION FOR ALL AVAILABLE COUPLES
for (dir in list_dirs){
  list_sim[[dir]] <- list()
  sim_path <- file.path(intervention_path, 'out', dir, 'results')
  rdata_files <- list.files(sim_path, pattern = "^sim_.*\\.RData$", full.names = F)
  invisible(lapply(rdata_files, function(file) load_rdata_to_list(file, list_sim, dir)))
}
```

## FOR EACH SIMULATION -> COMPUTE SAR
```{r}
## CATEGORY GROUPING INTO TYPE
cat_paramedical <- c("nurse", "student nurse", "aux nurse")
cat_medical <- c("physician", "ext physician", "reeducation staff", "other")

## IDS BY CATEGORY
id_patient <- admission_sim %>% filter(info == 0) %>% distinct(id) %>% pull()
id_hcw <- admission_sim %>% filter(info == 1) %>% distinct(id) %>% pull()
## FOR MEDICAL/PARAMEDICAL WE USE ADMISSION (INDIVIDUALS BEFORE ADDING NEW PATIENTS)
id_paramedical <- admission %>% filter(cat %in% cat_paramedical) %>% distinct(id) %>% pull()
id_medical <- admission %>% filter(cat %in% cat_medical) %>% distinct(id) %>% pull()

## GET SARs FOR ALL COUPLES
list_SAR <- get_all_SAR(list_sim = list_sim, 
                        id_patient = id_patient, 
                        id_hcw = id_hcw, 
                        id_paramedical = id_paramedical, 
                        id_medical = id_medical)

```

## SAR METRICS
```{r}
all_SAR_metrics <- get_all_SAR_metrics(list_SAR)

##SELECT COUPLES FOR SAR +/- 20%
all_SAR_metrics %>% filter(dplyr::between(SAR_median, 0.15, 0.25))
```

## SAR_distribution  
```{r}
get_SAR_distribution <- function(couple, list_SAR){
  SAR_distrib <- rbindlist(list_SAR[[couple]], idcol = 'id_sim')  %>% group_by(id_sim)
  return(SAR_distrib)
}
get_SAR_distribution(couple, list_SAR)
```




## FOR EACH SIMULATION -> COMPUTE SEIR COUNTS
```{r}
id_global <- global_status %>% distinct(id) %>% pull()
n_individual <- length(id_global)


list_SEIR <- list()

for(couple in names(list_sim)){
  parts <- strsplit(couple, "_")[[1]]
  beta <- eval(parse(text = gsub(pattern = '-', replacement = '/', x = parts[2])))
  nu <- eval(parse(text = gsub(pattern = '-', replacement = '/', x = parts[3])))
  
  list_SEIR[[couple]] <- SEIR_to_list(sim_list = list_sim[[couple]], n_subdivisions = new_n_subdivisions, n_individual = n_individual)

}
```



```{r}
fig_path <- file.path(intervention_path, id_sim, paste0(id_sim,"-fig"))

if (!dir.exists(fig_path)) {
  dir.create(fig_path, recursive = TRUE)
}
```

