---
title: "interaction-nodscov2"
author: "Olivier GAUFRÈS"
date: "2024-05-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(tidyverse)
library(ggplot2)
```

```{r}
wd <- getwd()
knitr::opts_chunk$set(root.dir = wd)

data_path <- file.path(wd,"..", "..", "data")
observed_path <- file.path(data_path,"data-observed")
synthetic_path <- file.path(data_path, "data-synthetic-graphs")
simplified_path <- file.path(data_path, "data-simplified")
expanded_path <- file.path(data_path,"data-expanded")
nodscov2_path <- file.path(data_path, "data-nodscov2") 
```

### WIP 

## NodsCov2 data (not shared)
```{r}
load("Y:/ogaufres/pacri-project/data/data-nodscov2/admission_ctc_nodscov2.RData")
load("Y:/ogaufres/pacri-project/data/data-nodscov2/list_ward.RData")
```

## FIXING ENCODING
```{r}
Encoding(admission$hospital) <- 'latin1'
```
## (TEMP)
```{r, include = FALSE}
write.csv2(admission, file = file.path(nodscov2_path, "nodscov2-csv","admission-nodscov2.csv"), row.names = FALSE)

sapply(names(list_ward),
 function (x) write.csv2(list_ward[[x]],
                         file = file.path(nodscov2_path,"nodscov2-csv",paste(x,"csv",sep="." )),
                         row.names = FALSE)   )
```

## MODIFY INDIVIDUAL IDS (include PA/PE in id)
```{r}
ldf <- lapply(names(list_ward), function(x) {
  df <- list_ward[[x]]
  df <- mutate(df, 
               from = paste0(admission[admission$id %in% df$from, "status"], "-", df$from),
               to = paste0(admission[admission$id %in% df$to, "status"], "-", df$to))
  return(df)
})
names(ldf) <- names(list_ward)

## Remove visitors
## Remove admin
## Remove investigators
##Remove logistics

```


## Data structure
```{r}
### ADMISSION = Individual's info
head(admission)
admission %>% distinct(hospital)

### LIST_WARD = LIST OF DATAFRAMES, EACH DF CONTAINS WARDS' INTERACTIONS
# Wards names
names(list_ward)
# Structures of wards df
head(list_ward$`Raymond_Poincare-Reanimation-20200506-20200507`)
```


## Individual proportions
```{r}
head(admission)

## Patients / HCW in all wards/hospitals
table(admission$status)

## Patients / HCW by cat (NA == patients)
table(admission$status, admission$cat, useNA = "always") 

## Proportion of individuals/ward etc..
table(admission$hospital, admission$ward)
```


## "FILTRATION"
```{r}
admission %>% filter(ward == "Reanimation")

## Ind in each reanimation ward
admission %>% filter(ward == "Reanimation") %>% group_by(hospital) %>% summarise( n = n(), .groups = "drop")

## Cat in each reanimation ward
admission %>% filter(ward == "Reanimation") %>% group_by(hospital, cat) %>% summarise( n = n(), .groups = "drop")
```


## PLOTS
```{r}
admission %>%
  filter(ward == "Reanimation") %>%
  group_by(hospital, cat) %>%
  summarise( n = n(), .groups = "drop") %>%
    ggplot(., aes(x = cat, y = n)) +
    geom_bar(stat = "identity") +
    facet_grid(cols = vars(hospital)) +
    theme_bw() +
    theme(axis.text.x = element_text(angle = 35, hjust = 1))
```


### "Edouard_Herriot-ReaChirurgie-20200616-20200617"
```{r}

EH_ReaChir <- list_ward$`Edouard_Herriot-ReaChirurgie-20200616-20200617`
```


### "Edouard_Herriot-Reanimation-20200609-20200610"
```{r}
EH_Rea <- list_ward$`Edouard_Herriot-Reanimation-20200609-20200610`
```


### "Necker-Reanimation-20200525-20200526"
```{r}
Necker_Rea <- list_ward$`Edouard_Herriot-Reanimation-20200609-20200610`
```


### "Raymond_Poincare-Reanimation-20200506-20200507"
```{r}
EH_Rea <- list_ward$`Edouard_Herriot-Reanimation-20200609-20200610`
```

